### ISSUE TITLE
Save acquisition JSON file from tile metadata

### ISSUE THREAD

**Issue by adamkglaser** [AllenNeuralDynamics/exaspim-control#11]
Save and convert/output the tile metadata dictionary to the aind-data-schema acquisition JSON spec.

- [ ] create a new launch repo outside of exaspim-control
- [ ] save the executed tile dictionary into the acquisition YAML file
- [ ] parse this tile dictionary from the YAML file into the aind-data-schema acquisition JSION spec

**Comment by micahwoodard** [comment]
@adamkglaser why do we need a separate launch script? TO me, it seems like we can just parse at end of scan

**Comment by micahwoodard** [comment]
Oh is it because we don't want to imbed the schema within the exaspim-control class? I guess that makes sense

**Comment by adamkglaser** [comment]
Yeah that is what I was thinking.
